# Use root/example as user/password credentials
version: 'latest'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: